version: '3.9'

services:
  matrixbackend:
    container_name: matrix-backend
    image: "node:16"
    working_dir: /home/node/app
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      NODE_ENV: prod
      MONGO_USER: root
      MONGO_PASSWORD: platypus
      MONGO_HOST: mongo
    volumes:
      - ./back:/home/node/app:z
    networks:
      - int_traefik
      - mongo
      - net_default
    #expose:
    #  - "8080:8080"
    command: "yarn run launch"
    labels:
      traefik.http.routers.42matrix-back.rule: (Host(`42.slopez.dev`) && PathPrefix(`/api`))
      traefik.http.services.42matrix-back.loadbalancer.server.port: 8080
      traefik.enable: true


  matrixfrontend:
    image: matrix-front
    restart: unless-stopped
    networks:
      - int_traefik
    labels:
      traefik.http.routers.42matrix-front.rule: (Host(`42.slopez.dev`))
      traefik.http.services.42matrix-front.loadbalancer.server.port: 3000
      traefik.enable: true

  mongo:
    image: mongo:4.4.18
    command:
      - '--wiredTigerCacheSizeGB'
      - '0.25'
    restart: unless-stopped
    networks:
      - mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: platypus

networks:
  int_traefik:
  mongo:
    name: mongo_global
    attachable: true
    internal: true
  net_default:
